export const siteConfig = {
  name: "Asliddin Nuriddinov - Programming Engineer",
  authorName: "Asliddin Nuriddinov",
  username: "aslnuriddinov",
  description: "Asliddin Nuriddinov - Dasturchi muhandislik ishlari!",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https:t.me/Asliddinjan_N",
    github: "https://github.com/Asliddin0807",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/public/image.png",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Asliddin Nuriddinov",
    "Applied AI Engineer",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
